name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.2
              with:
                  node-version: 14
            - run: yarn install --ci
            - run: yarn typedoc src/index.ts
            - run: git config --global user.email gerrit@gerritbirkeland.com
            - run: git config --global user.name "Gerrit Birkeland"
            - run: yarn gh-pages -d docs
