name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.2
              with:
                  node-version: 14
            - run: yarn install --ci
            - run: yarn typedoc src/index.ts
            - run: git config --global user.email typedoc@gerritbirkeland.com
            - run: git config --global user.name "TypeDoc Bot"
            - uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: docs
                  CLEAN: true
